import numpy as np

# These are based on the original csv file names
# Note that these column names may sometimes have spaces
# Preprocessing steps should get rid of these spaces so don't
# use these constants for processed data...
wq_cols = {
    "StationCode": "O",
    # "isSWMP": "O",
    "DateTimeStamp": np.datetime64,
    "Historical": np.int32,
    "ProvisionalPlus": np.int32,
    "F_Record": "O",
    "Temp": np.float32,
    "F_Temp": "O",
    "SpCond": np.float32,
    "F_SpCond": "O",
    "Sal": np.float32,
    "F_Sal": "O",
    "DO_Pct": np.float32,
    "F_DO_Pct": "O",
    "DO_mgl": np.float32,
    "F_DO_mgl": "O",
    "Depth": np.float32,
    "F_Depth": "O",
    "cDepth": np.float32,
    "F_cDepth": "O",
    "Level": np.float32,
    "F_Level": "O",
    "cLevel": np.float32,
    "F_cLevel": "O",
    "pH": np.float32,
    "F_pH": "O",
    "Turb": np.float32,
    "F_Turb": "O",
    "ChlFluor": np.float32,
    "F_ChlFluor": "O"
}

met_cols = {
    'StationCode': "O",
    # 'isSWMP': "O",
    'DatetimeStamp': np.datetime64,
    'Historical': np.int32,
    'ProvisionalPlus': np.int32,
    'Frequency': np.int32,
    'F_Record': "O",
    'ATemp': np.float32,
    'F_ATemp': "O",
    'RH': np.float32,
    'F_RH': "O",
    'BP': np.float32,
    'F_BP': "O",
    'WSpd': np.float32,
    'F_WSpd': "O",
    'MaxWSpd': np.float32,
    'F_MaxWSpd': "O",
    # This is duration
    'MaxWSpdT': "O",
    'Wdir': np.float32,
    'F_Wdir': "O",
    'SDWDir': np.float32,
    'F_SDWDir': "O",
    'TotPAR': np.float32,
    'F_TotPAR': "O",
    'TotPrcp': np.float32,
    'F_TotPrcp': "O",
    'TotSoRad': np.float32,
    'F_TotSoRad': "O",
}

nut_cols = {
    'StationCode': "O",
    # 'isSWMP': "O",
    'DateTimeStamp': np.datetime64,
    'Historical': np.int32,
    'ProvisionalPlus': np.int32,
    # 'CollMethd': np.int32,
    'REP': "O",
    'F_Record': "O",
    'PO4F': np.float32,
    'F_PO4F': "O",
    'NH4F': np.float32,
    'F_NH4F': "O",
    'NO2F': np.float32,
    'F_NO2F': "O",
    'NO3F': np.float32,
    'F_NO3F': "O",
    'NO23F': np.float32,
    'F_NO23F': "O",
    'CHLA_N': np.float32,
    'F_CHLA_N': "O",
}

# NOTE: Some of the columns have spaces in the source...
station_cols = {
    # 'Row',
    'NERR Site ID ': "O",
    'Station Code': "O",
    'Station Name': "O",
    # 'Lat Long',
    'Latitude ': np.float32,
    ' Longitude': np.float32,
    ' Status': "O",
    ' Active Dates': "O",
    ' State': "O",
    ' Reserve Name': "O",
    # 'Real Time',
    # 'HADS ID',
    'GMT Offset': "O",
    # 'Station Type',
    # 'Region',
    # 'isSWMP': "O",
    'Parameters Reported': "O"
}
